mill {
  # When running mill, which binary to invoke
  binary = "./mill"
  binary = ${?CELLAR_MILL_BINARY}
}

sbt {
  # When running sbt, which binary to invoke (sbt or sbtn)
  binary = "sbt"
  binary = ${?CELLAR_SBT_BINARY}
  # Whether to use client mode (--client) or not (--batch) when running sbt.
  # Client mode is much faster in case there is a running sbt server.
  use-client-mode = false
  binary = ${?CELLAR_SBT_CLIENT_MODE}
}